@startuml
autonumber

Producer -> Broker: 发送半消息
Broker -> Broker: 转移到内部topic
Producer -> Producer: 执行本地事务
Producer -> Broker: commit/rollback 确认消息

Broker -> Producer: 回查状态
Producer -> Broker: 根据本地事务执行状态发送commit/rollback

Broker -> Consumer: 消费消息
@enduml